version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker run --rm --privileged multiarch/qemu-user-static:register
     - run: docker login --username $DOCKER_USER --password $DOCKER_PASS
     - run: docker build -t chfanghr/arm-docker-in-docker:latest .
     - run: docker push chfanghr/arm-docker-in-docker:latest   